NAME = BraiiiiiiinnnzzzZ
SCRS = main.cpp Zombie.cpp newZombie.cpp randomChump.cpp
FLAGS = -Wall -Wextra -Werror

$(NAME): g++ $(FLAGS) $(SRCS) -o $(NAME)

all: $(NAME)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean all
